// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqoL1jF2VrVDl4Jj39mA_UnP-bCcCU_9c',
    appId: '1:462115136300:web:6bc89b0ea207afcec68289',
    messagingSenderId: '462115136300',
    projectId: 'flutter-flower-a2019',
    authDomain: 'flutter-flower-a2019.firebaseapp.com',
    storageBucket: 'flutter-flower-a2019.appspot.com',
    measurementId: 'G-F9TQ6F9RY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQcCGFa9HfH9HEB-6fLAoSN3PHWzF60A',
    appId: '1:462115136300:android:19c13ca8c22f515dc68289',
    messagingSenderId: '462115136300',
    projectId: 'flutter-flower-a2019',
    storageBucket: 'flutter-flower-a2019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIt_8ojhn3i5dk36Rqz8uksIw0FGAuCOk',
    appId: '1:462115136300:ios:ac4feda4f80db84fc68289',
    messagingSenderId: '462115136300',
    projectId: 'flutter-flower-a2019',
    storageBucket: 'flutter-flower-a2019.appspot.com',
    iosBundleId: 'com.example.flower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIt_8ojhn3i5dk36Rqz8uksIw0FGAuCOk',
    appId: '1:462115136300:ios:bf0ec684986416b7c68289',
    messagingSenderId: '462115136300',
    projectId: 'flutter-flower-a2019',
    storageBucket: 'flutter-flower-a2019.appspot.com',
    iosBundleId: 'com.example.flower.RunnerTests',
  );
}
